apiVersion: apps/v1
kind: Deployment
metadata:
  name: device
  namespace: smtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device
  template:
    metadata:
      labels:
        app: device
    spec:
      containers:
      - name: device
        image: siamatic/smtrack-device-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 100m
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: device-config
              key: DATABASE_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: device-config
              key: PORT
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: DEVICE_SECRET
          valueFrom:
            configMapKeyRef:
              name: jwt-secret
              key: DEVICE_SECRET
        - name: LOG_URL
          valueFrom:
            configMapKeyRef:
              name: device-config
              key: LOG_URL
        - name: UPLOAD_PATH
          valueFrom:
            configMapKeyRef:
              name: device-config
              key: UPLOAD_PATH
        - name: RADIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: RADIS_HOST
        - name: RADIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: RADIS_PASSWORD
        - name: RABBITMQ
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: device-config
              key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: device
  namespace: smtrack
spec:
  selector:
    app: device
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP